In [1]:
print('Baseline')

# This is so that you don't have to restart the kernel everytime you edit hmm.py

%load_ext autoreload
%autoreload 2

Baseline


In [2]:
from preprocess import load_arguments, load_label, load_values_from_json, combine_columns, split_arguments
from model import train_bert_model
import os

# Load arguments
df_arguments = load_arguments('data/arguments-training.tsv')

# Load json
human_values = load_values_from_json('data/value-categories.json')

df_labels = load_label("data/labels-training.tsv", human_values["1"])
df_full_level = combine_columns(df_arguments, df_labels)
train_arguments, valid_arguments = split_arguments(df_full_level)

train_arguments.info()
valid_arguments.info()

<class 'AttributeError'>
<class 'pandas.core.frame.DataFrame'>
Int64Index: 4176 entries, 3401 to 3031
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Argument ID                 4176 non-null   object
 1   Conclusion                  4176 non-null   object
 2   Stance                      4176 non-null   object
 3   Premise                     4176 non-null   object
 4   Achievement                 4176 non-null   int64 
 5   Benevolence: caring         4176 non-null   int64 
 6   Benevolence: dependability  4176 non-null   int64 
 7   Conformity: interpersonal   4176 non-null   int64 
 8   Conformity: rules           4176 non-null   int64 
 9   Face                        4176 non-null   int64 
 10  Hedonism                    4176 non-null   int64 
 11  Humility                    4176 non-null   int64 
 12  Power: dominance            4176 non-null   int64 
 13  Power: resources    

## Random Baseline

In [7]:
from pprint import pprint

from baseline import random_prediction
from metrics import compute_metrics, print_metrics
from utils import extract_true_labels



random_prediction_values = random_prediction(human_values['1'], train_arguments)

metrics = compute_metrics((random_prediction_values, 
                           extract_true_labels(train_arguments, human_values['1'])), human_values['1'])

pprint(metrics)

Random Prediction
Added predictions for 4176 arguments
{'accuracy_thresh': 0.27721503376960754,
 'f1-score': {'Achievement': 0.403,
              'Benevolence: caring': 0.401,
              'Benevolence: dependability': 0.254,
              'Conformity: interpersonal': 0.082,
              'Conformity: rules': 0.356,
              'Face': 0.135,
              'Hedonism': 0.078,
              'Humility': 0.157,
              'Power: dominance': 0.16,
              'Power: resources': 0.182,
              'Security: personal': 0.524,
              'Security: societal': 0.447,
              'Self-direction: action': 0.408,
              'Self-direction: thought': 0.297,
              'Stimulation': 0.107,
              'Tradition': 0.197,
              'Universalism: concern': 0.476,
              'Universalism: nature': 0.124,
              'Universalism: objectivity': 0.29,
              'Universalism: tolerance': 0.227,
              'avg-f1-score': 0.265},
 'marco-avg-f1score': 0.265}

## All 1 predictions


In [ ]:
from baseline import all_ones

one_values = all_ones(human_values['1'], train_arguments)

metrics = compute_metrics((one_values, 
                           extract_true_labels(train_arguments, human_values['1'])), human_values['1'])

pprint(metrics)

In [ ]:
bert_model_evaluation = train_bert_model(train_arguments, 'model', human_values['1'])
print(bert_model_evaluation['eval_f1-score'])

  0%|          | 0/4176 [00:00<?, ?ex/s]

  0%|          | 0/4176 [00:00<?, ?ex/s]

  0%|          | 0/4176 [00:00<?, ?ex/s]

  0%|          | 0/4176 [00:00<?, ?ex/s]

Some weights of the model checkpoint at prajjwal1/bert-small were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initi

***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-0.99586725 -0.3767782  -1.618691   ... -2.2841845  -1.493223
  -1.4191581 ]
 [-1.445169   -1.2008815  -1.8080845  ... -2.4601068  -1.5646787
  -1.9591643 ]
 [-1.5797155  -0.37761506 -1.758961   ... -1.5491625  -1.4218438
  -1.1616701 ]
 ...
 [-0.86567724 -0.32090092 -1.2826891  ... -1.7032816  -1.4690279
  -1.2585807 ]
 [-1.4079206  -1.2061942  -1.7336397  ... -2.1175778  -1.4920988
  -1.9853396 ]
 [-1.2371757  -1.20544    -1.6988695  ... -2.503446   -1.5996706
  -2.1539276 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-500
Configuration saved in model\checkpoint-500\config.json
Model weights saved in model\checkpoint-500\pytorch_model.bin
tokenizer config file saved in model\checkpoint-500\tokenizer_config.json
Special tokens file saved in model\checkpoint-500\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-0.66032916 -0.5756153  -1.8054469  ... -3.4041777  -2.0733032
  -2.001844  ]
 [-1.9089694  -0.9590259  -1.7900207  ... -2.8897045  -1.6647724
  -1.6906267 ]
 [-2.2018466  -0.73979414 -1.993017   ... -1.6972917  -1.5490193
  -1.0285108 ]
 ...
 [-1.1492139  -0.34299868 -1.2520925  ... -1.7401323  -1.8486053
  -2.0795798 ]
 [-1.4318492  -1.4806254  -1.9024537  ... -2.5247517  -1.9043677
  -2.4670653 ]
 [-0.471707   -0.9579265  -1.6186177  ... -3.3656616  -1.7424321
  -2.3157954 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-1000
Configuration saved in model\checkpoint-1000\config.json
Model weights saved in model\checkpoint-1000\pytorch_model.bin
tokenizer config file saved in model\checkpoint-1000\tokenizer_config.json
Special tokens file saved in model\checkpoint-1000\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-0.6977703  -0.70429784 -1.5928936  ... -3.8277006  -2.0035567
  -2.0153627 ]
 [-2.5178118  -1.227517   -1.7649035  ... -3.2772493  -1.6338599
  -1.48266   ]
 [-2.3660383  -1.0492253  -2.113728   ... -2.2580276  -1.4622614
  -0.82376915]
 ...
 [-1.6143966  -0.7123451  -0.71345496 ... -1.7768745  -1.6909084
  -2.377874  ]
 [-1.4009256  -1.7149452  -1.884306   ... -3.054669   -1.9003149
  -2.6594615 ]
 [-0.75414306 -1.1172445  -1.6618327  ... -4.0361285  -1.7833062
  -2.240342  ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-1500
Configuration saved in model\checkpoint-1500\config.json
Model weights saved in model\checkpoint-1500\pytorch_model.bin
tokenizer config file saved in model\checkpoint-1500\tokenizer_config.json
Special tokens file saved in model\checkpoint-1500\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-1.0839216  -0.43375742 -1.3302441  ... -3.6918364  -2.2460656
  -1.991411  ]
 [-2.8685415  -0.83797485 -1.8638129  ... -4.0049715  -1.6669064
  -1.1944611 ]
 [-2.580461   -1.0639744  -2.4100552  ... -2.6230488  -1.5402813
  -0.46484664]
 ...
 [-1.8393244  -0.75750875 -0.83563024 ... -2.092222   -1.9142787
  -2.4615285 ]
 [-1.6088884  -1.6345752  -1.9759625  ... -3.246694   -2.0230885
  -3.0647001 ]
 [-0.7756628  -0.5969174  -1.628373   ... -4.291505   -1.9137481
  -2.3933187 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-2000
Configuration saved in model\checkpoint-2000\config.json
Model weights saved in model\checkpoint-2000\pytorch_model.bin
tokenizer config file saved in model\checkpoint-2000\tokenizer_config.json
Special tokens file saved in model\checkpoint-2000\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-1.5487218  -0.95781976 -1.526781   ... -3.6475346  -1.8969129
  -1.8763027 ]
 [-2.6814308  -0.85272294 -1.8022249  ... -4.228257   -1.6241359
  -1.1018124 ]
 [-2.495914   -0.8655821  -2.3987641  ... -2.5479164  -1.3273237
   0.01429927]
 ...
 [-1.8924335  -0.70817614 -0.60448706 ... -1.9176644  -2.0211694
  -2.6297736 ]
 [-1.4522673  -1.8218279  -2.091036   ... -3.4255877  -2.2181296
  -3.2272613 ]
 [-1.0895567  -0.536473   -1.6640244  ... -4.794584   -2.1493554
  -2.3100114 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-2500
Configuration saved in model\checkpoint-2500\config.json
Model weights saved in model\checkpoint-2500\pytorch_model.bin
tokenizer config file saved in model\checkpoint-2500\tokenizer_config.json
Special tokens file saved in model\checkpoint-2500\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-1.6977692  -0.79589915 -1.3830302  ... -3.2416897  -1.2795619
  -1.5387716 ]
 [-2.842717   -0.7605578  -1.9621949  ... -4.4893684  -1.2550279
  -0.5041175 ]
 [-2.7625608  -0.90272707 -2.684544   ... -2.8826535  -1.4239016
  -0.13252366]
 ...
 [-2.1349163  -0.6717501  -0.4777091  ... -1.7253554  -2.1667876
  -2.5121646 ]
 [-1.4219198  -1.7239165  -2.1265688  ... -3.460277   -2.2357998
  -3.2490406 ]
 [-0.9473982  -0.02293292 -1.4686077  ... -4.679798   -2.0230565
  -1.9145645 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-3000
Configuration saved in model\checkpoint-3000\config.json
Model weights saved in model\checkpoint-3000\pytorch_model.bin
tokenizer config file saved in model\checkpoint-3000\tokenizer_config.json
Special tokens file saved in model\checkpoint-3000\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-1.9806805  -1.1143949  -1.2828891  ... -3.3883886  -1.2931874
  -1.8015914 ]
 [-3.1914618  -0.9577099  -2.1202579  ... -4.953905   -1.6978264
  -0.63838047]
 [-2.7042813  -1.0249504  -2.7818673  ... -2.9211168  -1.2756789
   0.32923773]
 ...
 [-2.279488   -1.1795281  -0.2515972  ... -1.9935608  -2.0187356
  -2.5823994 ]
 [-1.7044549  -1.8311856  -2.3681839  ... -3.9757843  -2.6758018
  -3.6132236 ]
 [-1.3857572  -0.58922243 -1.8129779  ... -5.456257   -2.4803355
  -2.3162003 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-3500
Configuration saved in model\checkpoint-3500\config.json
Model weights saved in model\checkpoint-3500\pytorch_model.bin
tokenizer config file saved in model\checkpoint-3500\tokenizer_config.json
Special tokens file saved in model\checkpoint-3500\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-1.9886739  -1.572221   -0.9821259  ... -3.0436869  -0.855272
  -1.790288  ]
 [-3.4831095  -1.4393301  -2.1388807  ... -5.1193104  -1.7114687
  -0.8708465 ]
 [-2.918143   -0.9078186  -2.8919573  ... -2.9346182  -1.3521475
   0.543015  ]
 ...
 [-2.1873317  -1.5155869  -0.19256522 ... -1.9721799  -1.9566251
  -2.801208  ]
 [-1.010669   -1.9166342  -2.3130307  ... -4.2147894  -2.6852694
  -3.4150898 ]
 [-1.30478    -0.95129466 -1.6808566  ... -5.466354   -2.6672883
  -2.7679684 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-4000
Configuration saved in model\checkpoint-4000\config.json
Model weights saved in model\checkpoint-4000\pytorch_model.bin
tokenizer config file saved in model\checkpoint-4000\tokenizer_config.json
Special tokens file saved in model\checkpoint-4000\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-2.236542   -1.6039124  -0.5559064  ... -2.240271   -0.13223806
  -1.6101947 ]
 [-4.233346   -1.4267821  -2.215426   ... -4.8685017  -2.2178068
  -0.6224235 ]
 [-3.0822742  -0.28383094 -2.8978274  ... -2.88123    -1.4816251
   0.7665662 ]
 ...
 [-2.2627187  -1.2080569  -0.27693868 ... -2.4490337  -1.8985548
  -3.0421185 ]
 [-1.3144767  -1.7076752  -2.6903572  ... -4.1724033  -2.989625
  -3.693903  ]
 [-2.0586333  -0.228881   -1.7872002  ... -5.571581   -3.0132074
  -2.5003152 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-4500
Configuration saved in model\checkpoint-4500\config.json
Model weights saved in model\checkpoint-4500\pytorch_model.bin
tokenizer config file saved in model\checkpoint-4500\tokenizer_config.json
Special tokens file saved in model\checkpoint-4500\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-2.6074762  -1.7268702  -0.708203   ... -2.3378358  -0.29578638
  -1.6315602 ]
 [-4.471305   -1.4654095  -2.1891398  ... -4.953129   -2.4436402
  -0.9574228 ]
 [-2.9494576   0.04715278 -3.1129234  ... -3.0468898  -1.6420794
   0.94735897]
 ...
 [-2.598476   -1.3141024  -0.03598842 ... -2.2787118  -2.1540334
  -2.9603915 ]
 [-1.4174495  -2.0969615  -2.5881567  ... -4.2532334  -3.026553
  -3.6287942 ]
 [-2.1650956  -0.16540441 -1.7239252  ... -5.423764   -3.1625683
  -2.3213816 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-5000
Configuration saved in model\checkpoint-5000\config.json
Model weights saved in model\checkpoint-5000\pytorch_model.bin
tokenizer config file saved in model\checkpoint-5000\tokenizer_config.json
Special tokens file saved in model\checkpoint-5000\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-2.54215    -1.796254   -0.7937524  ... -2.1930583   0.04676702
  -1.3992277 ]
 [-4.682432   -1.5957909  -2.2861805  ... -4.871291   -2.5733347
  -1.0241528 ]
 [-2.7952437   0.41114786 -3.0713425  ... -2.4475489  -1.2308716
   1.6000886 ]
 ...
 [-2.562933   -1.3953933   0.25430647 ... -2.2114964  -1.9187787
  -2.8946795 ]
 [-1.1901999  -1.9648995  -2.8789139  ... -4.7342014  -3.050952
  -3.408648  ]
 [-2.069273   -0.30015847 -1.8328893  ... -5.4917517  -3.1090865
  -2.2084966 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-5500
Configuration saved in model\checkpoint-5500\config.json
Model weights saved in model\checkpoint-5500\pytorch_model.bin
tokenizer config file saved in model\checkpoint-5500\tokenizer_config.json
Special tokens file saved in model\checkpoint-5500\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-2.3591661  -2.028615   -0.5918034  ... -1.7635392   0.5374176
  -1.397761  ]
 [-4.708477   -1.8920804  -2.446717   ... -5.165656   -2.4674282
  -0.8782112 ]
 [-2.7871296   0.9276389  -3.1191132  ... -2.528279   -1.4725198
   1.7102277 ]
 ...
 [-2.6187744  -2.0579867   0.30948418 ... -2.0023386  -1.9668936
  -2.9107218 ]
 [-1.15894    -2.2454345  -2.8700614  ... -4.7457685  -3.3580523
  -3.8349257 ]
 [-1.9011471  -0.53018904 -1.9795599  ... -5.7512045  -3.3988771
  -2.6550908 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-6000
Configuration saved in model\checkpoint-6000\config.json
Model weights saved in model\checkpoint-6000\pytorch_model.bin
tokenizer config file saved in model\checkpoint-6000\tokenizer_config.json
Special tokens file saved in model\checkpoint-6000\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-2.044266   -2.1199324  -0.36941814 ... -1.8686059   0.75933444
  -1.4023674 ]
 [-4.482907   -1.8629525  -2.4819136  ... -5.3121347  -2.399824
  -0.7186478 ]
 [-3.1336343   0.3690537  -3.1880784  ... -2.7321134  -1.6513419
   1.5444409 ]
 ...
 [-2.324767   -1.4654801   0.22770926 ... -2.6301308  -1.7593845
  -3.054852  ]
 [-0.7112258  -2.199721   -2.8629887  ... -4.651863   -3.1588717
  -3.6907768 ]
 [-1.4308047  -0.23278177 -1.9709668  ... -5.93983    -3.126945
  -2.325636  ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-6500
Configuration saved in model\checkpoint-6500\config.json
Model weights saved in model\checkpoint-6500\pytorch_model.bin
tokenizer config file saved in model\checkpoint-6500\tokenizer_config.json
Special tokens file saved in model\checkpoint-6500\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-2.4653542  -2.3037546  -0.34745735 ... -1.4556726   0.8992058
  -1.3127592 ]
 [-5.0004654  -1.9699733  -2.6788344  ... -5.183042   -2.8775902
  -0.55906165]
 [-3.2491965   0.45774454 -3.2042491  ... -2.5156796  -1.723923
   1.6815212 ]
 ...
 [-2.4789488  -1.9476295   0.4740619  ... -2.4395251  -1.9296943
  -3.0513778 ]
 [-1.1084387  -2.2357187  -2.9639678  ... -4.8529215  -3.3280544
  -3.633456  ]
 [-2.0657437  -0.32119194 -2.1715086  ... -5.9192643  -3.5798159
  -2.1720624 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-7000
Configuration saved in model\checkpoint-7000\config.json
Model weights saved in model\checkpoint-7000\pytorch_model.bin
tokenizer config file saved in model\checkpoint-7000\tokenizer_config.json
Special tokens file saved in model\checkpoint-7000\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-2.1637654  -2.218455   -0.34218985 ... -1.4556853   1.3037605
  -1.3443065 ]
 [-4.8227015  -1.5815163  -2.8509529  ... -5.311803   -2.3720047
  -0.17167938]
 [-3.169148    1.1303178  -3.0504682  ... -2.094296   -1.4540678
   1.9951823 ]
 ...
 [-2.3177     -1.8685238   0.22590052 ... -2.7692113  -1.8909805
  -3.227003  ]
 [-1.0646086  -2.2215178  -3.3457522  ... -5.141654   -3.478829
  -3.7420557 ]
 [-2.1899815   0.09984158 -2.2174273  ... -5.855851   -3.344359
  -2.2289658 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-7500
Configuration saved in model\checkpoint-7500\config.json
Model weights saved in model\checkpoint-7500\pytorch_model.bin
tokenizer config file saved in model\checkpoint-7500\tokenizer_config.json
Special tokens file saved in model\checkpoint-7500\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-2.0749907  -2.245201   -0.23853643 ... -1.4704179   1.3694927
  -1.4331305 ]
 [-5.1037426  -2.0178003  -2.7916796  ... -5.2518873  -2.6307137
  -0.5247283 ]
 [-3.1657393   1.1937041  -3.0973678  ... -2.0744333  -1.5188184
   2.009674  ]
 ...
 [-2.2748744  -1.9749529   0.5924165  ... -2.6142244  -1.7536116
  -3.1415339 ]
 [-1.0457032  -2.2076497  -3.3528976  ... -4.9843235  -3.3284364
  -3.8241525 ]
 [-2.230671    0.41268677 -2.262735   ... -5.9082265  -3.2420843
  -2.062614  ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-8000
Configuration saved in model\checkpoint-8000\config.json
Model weights saved in model\checkpoint-8000\pytorch_model.bin
tokenizer config file saved in model\checkpoint-8000\tokenizer_config.json
Special tokens file saved in model\checkpoint-8000\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


Results:  [[-2.442029   -2.2736504  -0.20349635 ... -1.1790198   1.6591234
  -1.2417303 ]
 [-5.241252   -2.3119593  -2.996625   ... -5.289796   -2.6547022
  -0.41122437]
 [-3.2484      1.2395121  -3.1731482  ... -2.120273   -1.6078513
   1.9277811 ]
 ...
 [-2.3152776  -2.0733209   0.53355646 ... -2.4923716  -1.7801456
  -3.0719802 ]
 [-1.0812354  -2.4679484  -3.3221736  ... -4.9322977  -3.5209413
  -3.8006194 ]
 [-2.1942132   0.13273333 -2.283884   ... -5.962903   -3.508463
  -1.9925174 ]] [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


Saving model checkpoint to model\checkpoint-8500
Configuration saved in model\checkpoint-8500\config.json
Model weights saved in model\checkpoint-8500\pytorch_model.bin
tokenizer config file saved in model\checkpoint-8500\tokenizer_config.json
Special tokens file saved in model\checkpoint-8500\special_tokens_map.json
***** Running Evaluation *****
  Num examples = 4176
  Batch size = 8


In [ ]:
from model import predict_bert_model

preds = predict_bert_model(valid_arguments, os.path.join('model/', 'prajjwal1/bert-small'), human_values['1'])


In [70]:
print(len(valid_arguments))


1044


In [64]:
fro

In [85]:
from model import tokenize_and_encode, detokenize_and_decode

x = tokenize_and_encode(valid_arguments.head(2))
print(x)
y = detokenize_and_decode(x)
print(y)

Could not locate the tokenizer configuration file, will try to use the model config instead.
loading configuration file config.json from cache at C:\Users\akshi/.cache\huggingface\hub\models--prajjwal1--bert-small\snapshots\0ec5f86f27c1a77d704439db5e01c307ea11b9d4\config.json
Model config BertConfig {
  "_name_or_path": "prajjwal1/bert-small",
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 512,
  "initializer_range": 0.02,
  "intermediate_size": 2048,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 8,
  "num_hidden_layers": 4,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.24.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading file vocab.txt from cache at C:\Users\akshi/.cache\huggingface\hub\models--prajjwal1--bert-small\snapshots\0ec5f86f27c1a77d704439db5e01c

Could not locate the tokenizer configuration file, will try to use the model config instead.
loading configuration file config.json from cache at C:\Users\akshi/.cache\huggingface\hub\models--prajjwal1--bert-small\snapshots\0ec5f86f27c1a77d704439db5e01c307ea11b9d4\config.json
Model config BertConfig {
  "_name_or_path": "prajjwal1/bert-small",
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 512,
  "initializer_range": 0.02,
  "intermediate_size": 2048,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 8,
  "num_hidden_layers": 4,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.24.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading file vocab.txt from cache at C:\Users\akshi/.cache\huggingface\hub\models--prajjwal1--bert-small\snapshots\0ec5f86f27c1a77d704439db5e01c

[{'input_ids': tensor([[  101,  3510,  2003,  1996,  7209,  8426,  2000,  2619,  1010,  2065,
          2111,  2215,  2009,  2027,  2323,  2022,  3499,  4103,   102,  2114,
           102,  2057,  2323, 10824,  3510,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1]])}, {'input_ids': tensor([[  101,  3171, 17147,  3073,  1037,  2512,  1011,  2510,  2624,  7542,
          2000,  2224,  2114,  3032,  1012,   102,  2114,   102,  2057,  2323,
          2203,  1996,  2224,  1997,  3171, 17147,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1]])}]
[['[CLS] marriage is the ultimate commitment to someone, if people want it they should be allowrd [SEP] against [SEP] we should abandon marriage [SEP]'], ['[CLS] economic sanctions provide a non - military sanction to use against countries. [SEP] against [SEP] we should end the use of economic sancti